package enums

// Option ...
type Option int

const (
	// GetBooks Option ...
	GetBooks Option = 1
	// SortByAuthor Option ...
	SortByAuthor Option = 2
	// SearchByTitle Option ...
	SearchByTitle Option = 3
)
